services:
  openvpn:
    image: dperson/openvpn-client
    container_name: openvpn
    restart: unless-stopped
    ports:
      - 1935:1935/tcp # RTMP rtmp://localhost:1935/mystream?user=myuser&pass=mypass
      - 1936:1936/tcp # RTMP rtmps://localhost:1936/mystream?user=myuser&pass=mypass
      - 2935:2935/tcp # RTMPS rtmps://localhost:2935/mystream?user=myuser&pass=mypass
      - 2936:2936/tcp # RTMPS rtmps://localhost:2936/mystream?user=myuser&pass=mypass
      - 8000:8000/udp # RTSP UDP/RTP rtsp://localhost:8000/mystream
      - 8000:8001/udp # RTSP UDP/RTCP rtsp://localhost:8001/mystream
      - 8002:8002/udp # RTSP RTP Multicast
      - 8003:8003/udp # RTSP RTCP Multicast control
      - 8189:8189/udp # WebRTC ICE/UDP
      - 8322:8322/tcp # TCP/TLS/RTSPS rtsps://localhost:8322/mystream
      - 8554:8554/tcp # RTSP rtsp://localhost:8554/mystream
      - 8888:8888/tcp # HLS http://localhost:8888/mystream
      - 8889:8889/tcp # WebRTC http://localhost:8889/mystream and http://localhost:8889/mystream/whep
      - 8890:8890/udp # SRT UDP srt://localhost:8890?streamid=read:mystream:myuser:mypass
      - 5000:5000/tcp # WEB-UI http://localhost:5000/mystream
    dns: ['1.1.1.1', '8.8.8.8']
    cap_add: [NET_ADMIN]
    command: '-f /vpn/config.ovpn'
    volumes:
        # Set path to your ovpn config
      - ${PWD}/config.ovpn:/vpn/config.ovpn
  wyze-bridge:
    container_name: wyze-bridge
    restart: unless-stopped
    image: idisposablegithub365/wyze-bridge:latest
    depends_on: [openvpn]
    network_mode: service:openvpn
    environment:
      # [OPTIONAL] Credentials can be set in the WebUI
      # API Key and ID can be obtained from the wyze dev portal:
      # https://developer-api-console.wyze.com/#/apikey/view
      - WYZE_EMAIL=
      - WYZE_PASSWORD=
      - API_ID=
      - API_KEY=
      # [OPTIONAL] IP Address of the host to enable WebRTC e.g.,:
      # - WB_IP=192.168.1.122
      # WebUI and Stream authentication:
      # - WB_AUTH=True # Set to false to disable web and stream auth.
      # - WB_USERNAME=
      # - WB_PASSWORD=
